### ISSUE TITLE
Help with Usage

### ISSUE THREAD

**Issue by lars18th** [fish4terrisa-MSDSM/archriscv-term#9]
Hi @fish4terrisa-MSDSM ,

I want to test your App. However, it's not clear how to configure it. I've decompressed the "archriscv-demo-40g-v0.1.tar.gz" image. And I've configured "RVVM NVMe raw image" pointing to the "arch.img" file. However, when starting (Launch) nothing happends. So please could do you add more information about how to properly configure it? Thank you.

Futhermore, I suggest to add inside the tool a Command to CLOSE it. It doesn't have this functionality and it's difficult to close it when some goes wrong.

Regards.

**Comment by lars18th** [comment]
Hi @fish4terrisa-MSDSM ,

It seems that the problem is that the "opensbi image" is not found. I feel this is the problem because I can't see any message regarding the boot process. So please, could do you add to the releases package this file?

Futhermore, I suggest that you check the existence of the necessary files (NVMe and opensbi images) before launching the process. This will help users to understand why the process doesn't start.

Thank you.

**Comment by fish4terrisa-MSDSM** [comment]
Which version did you use? I have just fixed a bug in the v10.1.0,which can lead to opensbi image not found.Wait me for a test ....And,I just combined the opensbi image into the apk,so it is expected to work....

**Comment by fish4terrisa-MSDSM** [comment]
> Hi @fish4terrisa-MSDSM ,
> 
> It seems that the problem is that the "opensbi image" is not found. I feel this is the problem because I can't see any message regarding the boot process. So please, could do you add to the releases package this file?
> 
> Futhermore, I suggest that you check the existence of the necessary files (NVMe and opensbi images) before launching the process. This will help users to understand why the process doesn't start.
> 
> Thank you.

And,you need to uninstall the previous apk and install the new version,or it wont extract the opensbi image.

**Comment by lars18th** [comment]
Hi @fish4terrisa-MSDSM ,

Thank you for your response.

> Which version did you use? 

Last version v10.1.0 from https://github.com/fish4terrisa-MSDSM/archriscv-term/releases

Installed on a Android 13 stock without any type of root (in fact a Samsung device). After install it, I launch the App, I accept the two privileges, and when the Menu is shown I selected "Launch"... But after the system *never* starts.

I've tested to add/edit some paramters (like the "opensbi image"), but nothing helps. So please could you write a guide to install-and-start it? Or make a video. What you prefer.

Regards.

**Comment by fish4terrisa-MSDSM** [comment]
> Hi @fish4terrisa-MSDSM ,
> 
> Thank you for your response.
> 
> > Which version did you use?
> 
> Last version v10.1.0 from https://github.com/fish4terrisa-MSDSM/archriscv-term/releases
> 
> Installed on a Android 13 stock without any type of root (in fact a Samsung device). After install it, I launch the App, I accept the two privileges, and when the Menu is shown I selected "Launch"... But after the system _never_ starts.
> 
> I've tested to add/edit some paramters (like the "opensbi image"), but nothing helps. So please could you write a guide to install-and-start it? Or make a video. What you prefer.
> 
> Regards.

Hmm...I never tried it on android13,but it just worked well on android 10,so this might be a bug of android 13

**Comment by lars18th** [comment]
Hi @fish4terrisa-MSDSM ,

> Hmm...I never tried it on android13,but it just worked well on android 10,so this might be a bug of android 13

Then I'll try to check it on another device. Thank you.

**Comment by fish4terrisa-MSDSM** [comment]
Closed this issue as no further comment.

**Comment by lars18th** [comment]
> Closed this issue as no further comment.

Hi @fish4terrisa-MSDSM ,

I don't have time to test it. However, I suggest to extend the current README with a simple "first run how to". I feel the guide quite obscure to solve some problems.
In addition: You have added support for Android 13?

Regards.

**Comment by lars18th** [comment]
Hi @fish4terrisa-MSDSM ,

I need your help!
The documentation is still not clear enough on how to set it up.

Steps done:
- Install the APK of the last version `arch-linux-riscv64-term-aarch64-10.2.0.apk` from here: https://github.com/fish4terrisa-MSDSM/archriscv-term/releases/tag/v10.2.0
- Download the ROOT.IMG `archriscv-demo-40g-v0.1.tar.gz` from here: https://github.com/fish4terrisa-MSDSM/archriscv-term/releases/tag/v10.1.0
- Extracted the file `arch.img` and copy it to `/storage/0000-0000/RVVM/` (the physical external SD-CARD).
- Download the OpenSBI Image `fw_payload.bin` from here: https://github.com/LekKit/patches-misc/releases/tag/rvvm-uboot-2024.7
- Copy the `fw_payload.bin` to `/storage/0000-0000/RVVM/` 
- Get the Linux Kernel `linux_6.8` from here: https://github.com/LekKit/patches-misc/releases/tag/rvvm-linux-6.8
- Copy the `linux_6.8` to `/storage/0000-0000/RVVM/` 
- Launch the App and configure in Settings the three options (manually writing the full path of each file): `RVVM NVme raw image`, `OpenSBI Image` and `Kernel`. And don't touch any other option.
- The select "Launch"...

But **nothing** starts to run.

What I'm doing wrong? Android 14 in a sotck Samsung device.

**Comment by fish4terrisa-MSDSM** [comment]
In my test case, I just left the `Kernel` to be blank.(Yes, there's a u-boot in side the opensbi payload:)
As I just changed my device, I haven't tested archriscv-term on this device.(It's also a Android 14 device , runs on oneplus ace3) I'll have a test later.

**Comment by lars18th** [comment]
Thank you for the response.

> In my test case, I just left the `Kernel` to be blank.(Yes, there's a u-boot in side the opensbi payload:)

I recommend then to write a simple "Install/Setup" guide. These steps aren't clear.

> As I just changed my device, I haven't tested archriscv-term on this device.(It's also a Android 14 device , runs on oneplus ace3) I'll have a test later.

Nice! I want to see if it can run without troubles in Android 14.

**Comment by lars18th** [comment]
Hi @fish4terrisa-MSDSM ,

Any news about how to run it with Android 14 ?

**Comment by fish4terrisa-MSDSM** [comment]
> Hi @fish4terrisa-MSDSM ,
> 
> Any news about how to run it with Android 14 ?

I tried to port it to Android 14... But it seems that it cannot even load the libbash.so ..... I'm still working on it.(But I knows nearly nothing about java and android...) And... Since its just a wrapper around a bash script, you can just try to use termux and run RVVM inside instead :)

**Comment by fish4terrisa-MSDSM** [comment]
> > Hi @fish4terrisa-MSDSM ,
> > Any news about how to run it with Android 14 ?
> 
> I tried to port it to Android 14... But it seems that it cannot even load the libbash.so ..... I'm still working on it.(But I knows nearly nothing about java and android...) And... Since its just a wrapper around a bash script, you can just try to use termux and run RVVM inside instead :)

**Comment by lars18th** [comment]
Hi @fish4terrisa-MSDSM ,

Ok, Termux 😉 

So, share please the command/s to execute inside Termux. I don't found them inside the source code of the App.
